### PR TITLE
add course page + use prettier to format

### PR DESCRIPTION
**Pull request by nayasinghania**
The professorsTable and coursesTable both do not have  a starRating in the schema; so the ratings are just using fake data for now. I also formatted the file with prettier, which let to minor style changes in a few other files

image

### CODE REVIEW

**Review by joshua-demo — COMMENTED** [review]
in next js you don't need to import react, only when you are using any react hook, then do you need to import react

**Comment by nayasinghania** [comment]
doesn't look like i imported react in any of my code. the only place where react is imported is in the shadcn components, which were generated by shadcn

**Comment by joshua-demo** [comment]
> Member
ah, ok, i'll approve this pr now

**Review by joshua-demo — APPROVED** [review]
lgtm

**Pull request merged**
