### PR TITLE
Add DB check to github actions workflow

### PR DESCRIPTION
**Pull request by jonathanguven**
dont review yet just testing

### CODE REVIEW

**Comment by jonathanguven** [comment]
do we really need to add another postgres image for the CI. There might already be one because when I used port 5432 it said that port was already used.

**Comment by jonathanguven** [comment]
image
its already starting postgres image in the `Initialize Containers` CI step.

**Comment by gursheyss** [comment]
> image its already starting postgres image in the `Initialize Containers` CI step.



> image its already starting postgres image in the `Initialize Containers` CI step.

It's doing this after you added it, if u look at any other CI before you changed it this step doesnt happen

**Comment by gursheyss** [comment]
> do we really need to add another postgres image for the CI. There might already be one because when I used port 5432 it said that port was already used.

It's because you added `bun run db:dev` that tries to start up another instance, we're only supposed to use this locally cause the postgres container in the CI already gets started when you add it

**Comment by gursheyss** [comment]
Also need to update the database url envar to point to the one that starts in this container

**Review by gursheyss — APPROVED** [review]
i think its good

**Pull request merged**
